using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;
using UnityEngine.Video;
using Object = UnityEngine.Object;

namespace CruFramework.Editor.Tools
{
    /// <summary>
    /// アセットの結合・分離およびアニメーション周りの補助操作を提供するエディタツール。
    /// </summary>
    public class CombineAssetTool : EditorWindow
    {
        private const string AnimatorControllerExtension = ".controller";
        private const string RootMenuItemPath = "Assets/Combine Asset Tool/";
        private const int RootMenuItemPriority = int.MinValue;
        private const int AnimationGroupPriority = RootMenuItemPriority;
        private const int GeneralGroupPriority = RootMenuItemPriority + 50;
        private const int MinimumSelectionCount = 2;
        private const int FirstAssetIndex = 0;
        private const int SecondAssetIndex = 1;

        /// <summary>
        /// インポーターで管理されているため結合できないアセットタイプとそのエラーメッセージ
        /// </summary>
        private static readonly Dictionary<Type, string> UnsupportedAssetTypes = new()
        {
            { typeof(Texture2D), "Texture assets are managed by the Unity importer" },
            { typeof(Texture3D), "Texture assets are managed by the Unity importer" },
            { typeof(Cubemap), "Cubemap assets are managed by the Unity importer" },
            { typeof(RenderTexture), "RenderTexture assets are managed by the Unity importer" },
            { typeof(Sprite), "Sprites are generated by the Unity importer" },
            { typeof(AudioClip), "AudioClips are managed by the Unity importer" },
            { typeof(VideoClip), "VideoClips are managed by the Unity importer" }
        };

        /// <summary>
        /// 選択した複数のアセットを、先頭に選択したアセットへサブアセットとして結合します。
        /// </summary>
        [MenuItem(RootMenuItemPath + "Combine Assets To First Selected Item", priority = GeneralGroupPriority)]
        public static void CombineAssetsToFirst()
        {
            var assets = Selection.objects;
            if (!ValidateSelectionForCombine(assets) || !ValidateSelectedAssetsForCombine(assets, out var hostAsset)) return;

            foreach (var currentAsset in assets.Skip(SecondAssetIndex))
            {
                if (!ExecuteWithErrorHandling(() =>
                    {
                        CombineAssetWithSubAssets(currentAsset, hostAsset);
                        AssetDatabase.DeleteAsset(AssetDatabase.GetAssetPath(currentAsset));
                    }, currentAsset.name, "Asset", "Combine Failed"))
                    return;
            }

            AssetDatabase.SaveAssets();
        }

        /// <summary>
        /// 親アセットから選択中のサブアセットを削除します。
        /// </summary>
        [MenuItem(RootMenuItemPath + "Remove Selected Items From Nest Asset", priority = GeneralGroupPriority)]
        public static void RemoveAssets()
        {
            ExtractSubAssetsFromSelection(
                Selection.objects,
                AssetDatabase.IsSubAsset,
                asset => GenerateOutputPath(asset, GetDefaultExportExtension(asset)),
                "Asset",
                "Remove Failed"
            );
        }

        /// <summary>
        /// 1つの AnimatorController を選択し、外部の AnimationClip をそのサブアセットとして結合します。
        /// </summary>
        [MenuItem(RootMenuItemPath + "Animation Combine", priority = AnimationGroupPriority)]
        public static void CombineAnimationsToAnimator()
        {
            var assets = Selection.objects.ToList();
            var targetAnimator = ValidateSingleAnimatorController(assets);
            if (targetAnimator == null) return;

            var animationClips = assets.Where(a => a is AnimationClip && !IsNestedAnimationClip(a)).ToList();
            if (animationClips.Any(clip => !ValidateAssetCanInstantiate(clip, "Animation Clip"))) return;

            foreach (var clip in animationClips)
            {
                if (!ExecuteWithErrorHandling(() =>
                    {
                        var clipInstance = Instantiate(clip);
                        clipInstance.name = clip.name;
                        AssetDatabase.AddObjectToAsset(clipInstance, targetAnimator);
                        AssetDatabase.DeleteAsset(AssetDatabase.GetAssetPath(clip));
                    }, clip.name, "Animation Clip", "Combine Failed"))
                    return;
            }

            AssetDatabase.SaveAssets();
        }

        /// <summary>
        /// ネストされた AnimationClip を個別の .anim ファイルとして取り出し、AnimatorController から削除します。
        /// </summary>
        [MenuItem(RootMenuItemPath + "Animation Remove", priority = AnimationGroupPriority)]
        public static void RemoveNestedAnimations()
        {
            var assets = Selection.objects;
            if (!assets.Any(IsNestedAnimationClip)) { ShowErrorDialog("Animation Remove",
                    "No nested AnimationClip is selected.\n\nPlease pick an AnimationClip nested inside an AnimatorController."); return; }

            ExtractSubAssetsFromSelection(
                assets,
                IsNestedAnimationClip,
                asset => GenerateOutputPath(asset, ".anim"),
                "Animation Clip",
                "Remove Failed"
            );
        }

        /// <summary>
        /// 選択中のネストされた AnimationClip の名前を変更するウィンドウを開きます。
        /// </summary>
        [MenuItem(RootMenuItemPath + "Animation Rename", priority = AnimationGroupPriority)]
        public static void RenameNestedAnimation()
        {
            var clip = Selection.activeObject as AnimationClip;
            if (clip == null || !IsNestedAnimationClip(clip)) { ShowErrorDialog("Animation Rename",
                    "No nested AnimationClip is selected.\n\nPlease select exactly one AnimationClip nestled inside an AnimatorController."); return; }

            RenameNestedAssetWindow.ShowWindow(clip);
        }

        /// <summary>
        /// 選択中のネストされたアセット（サブアセット）の名前を変更するウィンドウを開きます。
        /// </summary>
        [MenuItem(RootMenuItemPath + "Rename Nested Asset", priority = GeneralGroupPriority)]
        public static void RenameNestedAsset()
        {
            var asset = Selection.activeObject;
            if (asset == null || !AssetDatabase.IsSubAsset(asset)) { Debug.LogWarning("CombineAssetTool: Please select one nested sub-asset."); return; }
            RenameNestedAssetWindow.ShowWindow(asset);
        }

        /// <summary>
        /// 選択されたアセットの基本的な条件を検証します。
        /// </summary>
        private static bool ValidateSelectionForCombine(Object[] assets) =>
            assets?.Length >= MinimumSelectionCount ||
            ShowErrorAndReturn("Cannot Combine Assets",
                "Select multiple assets.\nAt least two assets are required.", false);

        /// <summary>
        /// 選択されたアセットが結合可能かどうかを検証します。
        /// </summary>
        private static bool ValidateSelectedAssetsForCombine(Object[] assets, out Object hostAsset)
        {
            hostAsset = assets[FirstAssetIndex];

            if (!CanHostSubAssets(hostAsset, out var hostError))
                return ShowErrorAndReturn("Cannot Combine Assets",
                    $"The first selected asset '{hostAsset.name}' cannot host sub-assets:\n{hostError}", false);

            foreach (var asset in assets.Skip(SecondAssetIndex))
            {
                if (!ValidateAssetForCombine(asset)) return false;
            }

            return true;
        }

        /// <summary>
        /// 指定のアセットが AnimatorController 内にネストされた AnimationClip かどうかを判定します。
        /// </summary>
        private static bool IsNestedAnimationClip(Object asset) =>
            asset is AnimationClip && Path.GetExtension(AssetDatabase.GetAssetPath(asset)) == AnimatorControllerExtension;

        /// <summary>
        /// 指定オブジェクトを書き出す際の推奨拡張子を返します。
        /// </summary>
        private static string GetDefaultExportExtension(Object asset) =>
            asset switch
            {
                AnimationClip => ".anim",
                Material      => ".mat",
                _             => ".asset"
            };

        /// <summary>
        /// エラーダイアログを表示します。
        /// </summary>
        private static void ShowErrorDialog(string title, string message) =>
            EditorUtility.DisplayDialog(title, message, "OK");

        /// <summary>
        /// エラーダイアログを表示し、指定した値を返します。
        /// </summary>
        private static T ShowErrorAndReturn<T>(string title, string message, T result)
        {
            ShowErrorDialog(title, message);
            return result;
        }

        /// <summary>
        /// アセットの出力パスを生成します。
        /// </summary>
        private static string GenerateOutputPath(Object asset, string extension)
        {
            var assetPath = AssetDatabase.GetAssetPath(asset);
            var dir = Path.GetDirectoryName(assetPath);
            return AssetDatabase.GenerateUniqueAssetPath($"{dir}/{asset.name}{extension}");
        }

        /// <summary>
        /// 単一の AnimatorController が選択されているか検証します。
        /// </summary>
        private static AnimatorController ValidateSingleAnimatorController(List<Object> assets)
        {
            var animatorControllerCount = assets.Count(item => item is AnimatorController);

            if (animatorControllerCount == 0)
                return ShowErrorAndReturn("Animation Combine",
                    "No AnimatorController is selected.\n\nChoose one AnimatorController together with the AnimationClips you want to combine.",
                    (AnimatorController)null);

            if (animatorControllerCount > 1)
                return ShowErrorAndReturn("Animation Combine",
                    "Multiple AnimatorControllers are selected.\n\nPlease select only one AnimatorController.",
                    (AnimatorController)null);

            return assets.First(item => item is AnimatorController) as AnimatorController;
        }

        /// <summary>
        /// アセットが結合可能かどうかを検証し、失敗時はダイアログを表示して操作を中止します。
        /// サブアセットとして追加可能か、およびインスタンス化可能かをチェックします。
        /// </summary>
        private static bool ValidateAssetForCombine(Object asset)
        {
            if (!CanAddAsSubAsset(asset, out var errorMessage))
                return ShowErrorAndReturn("Cannot Combine Assets", errorMessage, false);

            return CanInstantiateAsset(asset, out errorMessage) || ShowErrorAndReturn("Cannot Combine Assets",
                $"Asset '{asset.name}' cannot be instantiated:\n{errorMessage}\n\nThe operation was cancelled.", false);
        }

        /// <summary>
        /// アセットがインスタンス化可能かどうかを検証し、失敗時はダイアログを表示して操作を中止します。
        /// </summary>
        private static bool ValidateAssetCanInstantiate(Object asset, string displayNoun)
        {
            return CanInstantiateAsset(asset, out var errorMessage) || ShowErrorAndReturn($"Cannot Combine {displayNoun}",
                $"{displayNoun} '{asset.name}' cannot be instantiated:\n{errorMessage}\n\nThe operation was cancelled.", false);
        }

        /// <summary>
        /// 例外処理付きで処理を実行します。
        /// </summary>
        private static bool ExecuteWithErrorHandling(Action action, string assetName, string displayNoun, string dialogTitle)
        {
            try
            {
                action();
                return true;
            }
            catch (Exception ex)
            {
                ShowErrorDialog(dialogTitle,
                    $"An error occurred while processing {displayNoun} '{assetName}':\n{ex.Message}\n\nThe operation was aborted.");
                AssetDatabase.SaveAssets();
                return false;
            }
        }

        /// <summary>
        /// アセットがサブアセットとして追加可能かどうかをチェックします。
        /// </summary>
        private static bool CanAddAsSubAsset(Object asset, out string errorMessage)
        {
            errorMessage = string.Empty;

            // AssetImporter で管理されているアセットはサブアセットとして追加できない
            var assetPath = AssetDatabase.GetAssetPath(asset);
            var importer = AssetImporter.GetAtPath(assetPath);

            // Importerが存在し、かつメインアセットがImporterで生成されたものの場合
            if (importer != null && !AssetDatabase.IsSubAsset(asset))
            {
                var assetType = asset.GetType();

                // サポートされていないアセットタイプをチェック
                if (UnsupportedAssetTypes.TryGetValue(assetType, out var reason))
                {
                    errorMessage = GenerateUnsupportedAssetErrorMessage(asset, assetType, reason);
                    return false;
                }

                if (asset is Mesh && importer is ModelImporter)
                {
                    errorMessage = $"Mesh '{asset.name}' cannot be combined.\n\n" +
                                   "Meshes generated from model files are managed by the Unity importer and cannot be added as sub-assets.";
                    return false;
                }
            }

            return true;
        }

        /// <summary>
        /// サポートされていないアセットタイプのエラーメッセージを生成します。
        /// </summary>
        private static string GenerateUnsupportedAssetErrorMessage(Object asset, Type assetType, string reason)
        {
            var baseMessage = $"{assetType.Name} '{asset.name}' cannot be combined.\n\n{reason}, so it cannot be added as a sub-asset.";
            
            if (assetType == typeof(Texture2D) || assetType == typeof(Texture3D) || 
                assetType == typeof(Cubemap) || assetType == typeof(RenderTexture))
            {
                return baseMessage + "\n\nSupported asset types include:\n" +
                       "- Material\n" +
                       "- AnimationClip (manually created)\n" +
                       "- ScriptableObject\n" +
                       "- AnimatorController, etc.";
            }
            
            return baseMessage;
        }

        /// <summary>
        /// アセットがインスタンス化可能かどうかをチェックします。
        /// </summary>
        private static bool CanInstantiateAsset(Object asset, out string errorMessage)
        {
            errorMessage = string.Empty;

            if (asset is Texture2D { isReadable: false } texture)
            {
                errorMessage = $"Texture '{texture.name}' is not readable.\nEnable the 'Read/Write Enabled' option in the Inspector.";
                return false;
            }

            return true;
        }

        /// <summary>
        /// 指定のアセットがサブアセットの親（格納先）になれるかをチェックします。
        /// Importer により管理される種別（Texture, Sprite, AudioClip, VideoClip, Model 由来の Mesh など）は不可。
        /// </summary>
        private static bool CanHostSubAssets(Object asset, out string errorMessage)
        {
            errorMessage = string.Empty;

            var assetPath = AssetDatabase.GetAssetPath(asset);
            var importer = AssetImporter.GetAtPath(assetPath);

            if (importer != null)
            {
                var assetType = asset.GetType();

                if (UnsupportedAssetTypes.TryGetValue(assetType, out var reason))
                {
                    errorMessage = $"{assetType.Name} '{asset.name}' cannot host sub-assets.\n{reason}, so it cannot contain sub-assets.";
                    return false;
                }

                if (asset is Mesh && importer is ModelImporter)
                {
                    errorMessage = $"Mesh '{asset.name}' cannot host sub-assets.\n" +
                                   "Meshes generated from model files are managed by the Unity importer and cannot contain sub-assets.";
                    return false;
                }
            }

            return true;
        }

        /// <summary>
        /// アセットとそのすべてのサブアセットを指定されたターゲットに結合します。
        /// </summary>
        private static void CombineAssetWithSubAssets(Object sourceAsset, Object targetAsset)
        {
            var assetPath = AssetDatabase.GetAssetPath(sourceAsset);
            var allAssets = AssetDatabase.LoadAllAssetsAtPath(assetPath);
            var mainAsset = AssetDatabase.LoadMainAssetAtPath(assetPath);

            var newMainAsset = Instantiate(mainAsset);
            newMainAsset.name = mainAsset.name;
            AssetDatabase.AddObjectToAsset(newMainAsset, targetAsset);

            foreach (var asset in allAssets.Where(a => a != mainAsset && AssetDatabase.IsSubAsset(a) && (a.hideFlags & HideFlags.HideInHierarchy) == 0))
            {
                var newSubAsset = Instantiate(asset);
                newSubAsset.name = asset.name;
                AssetDatabase.AddObjectToAsset(newSubAsset, newMainAsset);
            }
        }

        /// <summary>
        /// 選択中の対象サブアセットを外部ファイルとして抽出し、親から取り外します。
        /// </summary>
        private static void ExtractSubAssetsFromSelection(
            Object[] selection,
            Func<Object, bool> isTarget,
            Func<Object, string> computeOutputPath,
            string displayNoun,
            string failureTitle)
        {
            foreach (var asset in selection.Where(isTarget))
            {
                if (!ValidateAssetCanInstantiate(asset, displayNoun))
                    return;

                if (!ExecuteWithErrorHandling(() =>
                    {
                        var extracted = Instantiate(asset);
                        AssetDatabase.CreateAsset(extracted, computeOutputPath(asset));
                        AssetDatabase.RemoveObjectFromAsset(asset);
                        DestroyImmediate(asset);
                        AssetDatabase.SaveAssets();
                    }, asset.name, displayNoun, failureTitle))
                    return;
            }
        }

        /// <summary>
        /// ネストされたアセット（サブアセット）の名称変更用ミニウィンドウ。
        /// </summary>
        private sealed class RenameNestedAssetWindow : EditorWindow
        {
            private Object targetAsset;
            private string newName;

            /// <summary>
            /// リネーム画面表示
            /// </summary>
            public static void ShowWindow(Object asset)
            {
                var window = CreateInstance<RenameNestedAssetWindow>();
                window.titleContent = new GUIContent($"Rename {asset.GetType().Name}");
                window.targetAsset = asset;
                window.newName = asset.name;
                window.minSize = new Vector2(360, 90);
                window.maxSize = new Vector2(600, 120);
                window.ShowUtility();
            }

            /// <summary>
            /// GUIの描画処理
            /// </summary>
            private void OnGUI()
            {
                if (targetAsset != null)
                {
                    EditorGUILayout.LabelField($"Asset Type: {targetAsset.GetType().Name}", EditorStyles.helpBox);
                    GUILayout.Space(4);
                }

                EditorGUILayout.LabelField("New Name", EditorStyles.boldLabel);
                newName = EditorGUILayout.TextField(newName);

                GUILayout.Space(8);
                using (new EditorGUILayout.HorizontalScope())
                {
                    if (GUILayout.Button("Cancel"))
                        Close();

                    GUILayout.FlexibleSpace();

                    EditorGUI.BeginDisabledGroup(string.IsNullOrWhiteSpace(newName));
                    if (GUILayout.Button("Rename"))
                        ApplyRename();
                    EditorGUI.EndDisabledGroup();
                }
            }

            /// <summary>
            /// リネーム適用
            /// </summary>
            private void ApplyRename()
            {
                if (!targetAsset)
                {
                    Close();
                    return;
                }

                targetAsset.name = newName.Trim();
                EditorUtility.SetDirty(targetAsset);
                AssetDatabase.SaveAssets();
                Close();
            }
        }
    }
}
