using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using CruFramework.UI;
using MagicOnion;
using MagicOnion.Client;
using MessagePack;
using MessagePack.Resolvers;

namespace Pjfb
{
    [MagicOnionClientGeneration(typeof(IPjfbGameHub))]
    internal partial class MagicOnionClientInitializer
    {
    }
    
    public class MessagePackInitializer
    {
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
        static void RegisterResolvers()
        {
            UnityEngine.Debug.Log("Message pack resolver registered.");
            // NOTE: Currently, CompositeResolver doesn't work on Unity IL2CPP build. Use StaticCompositeResolver instead of it.
            StaticCompositeResolver.Instance.Register(
                // This resolver is generated by MagicOnion's code generator.
                MagicOnionClientInitializer.Resolver,
                // This resolver is generated by MessagePack's code generator.
                GeneratedResolver.Instance,
                BuiltinResolver.Instance,
                PrimitiveObjectResolver.Instance,
                StandardResolver.Instance
            );

            MessagePackSerializer.DefaultOptions = MessagePackSerializer.DefaultOptions
                .WithResolver(StaticCompositeResolver.Instance);
        }
    }
}